### ISSUE TITLE
Traduction for score tab 

### ISSUE THREAD

**Issue by Sacramentix** [Sacramentix/WikiAdventure#20]
In front-quasar\wiki-adventure-quasar\src\layouts\lobby\tab\ScoreTabPanel.vue lines 3 and 6

Translate the title and the leaderboard button

**Comment by arthurmadecprevost** [comment]
Added in these 2 commits:
e052c1eed57258dfad827a204f33c3c97f434cad for French translation,
7527e0c1ac72b9b2d102c6e0e4b19e20f0fea6a9 for English translation.

**Comment by Sacramentix** [comment]
fixed !
