### ISSUE TITLE
Traduction for wiki page placeholder

### ISSUE THREAD

**Issue by Sacramentix** [Sacramentix/WikiAdventure#23]
Traduction for the tips shown before the first the search phase, and end page placeholder " no end page yet "

**Comment by Sacramentix** [comment]
front-quasar\wiki-adventure-quasar\src\layouts\lobby\WikiPage.vue line 314

**Comment by arthurmadecprevost** [comment]
English translation commit: bede973f8e09f7a9a01cf4ca4d18c6e5947408c2
French translation commit: 588994bc5485d7dd7dd54c78189d5846ecaa9984

You have to rename the button **gameTab.wikiEndPage** by **gameTab.endPage** as the translation already exists.
